version: "3.8"

services:
  web:
    build: .
    container_name: fullstack_rails_app
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
#    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
