# How to run this image:
# - First build an imagem from this specification file : docker build --tag hello-world:1 .
# - The spawn a container from the image created       : docker run hello-world:1

# Now, change from "ubuntu" to "alpine"
# - First build an imagem from this specification file : docker build --tag hello-world:2 .
# - The spawn a container from the image created       : docker run hello-world:2

# Finally, see the size difference                     : docker images | grep hello-world


FROM ubuntu:latest

CMD echo "hello world"