version: "3.8"

services:
  api:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      # You can also already connect to the postgres container
    ports:
      - "8080:80"
